datastax-java-driver {
  basic {
    request {
      consistency = LOCAL_QUORUM
      timeout = 10 seconds
    }
    load-balancing-policy {
      local-datacenter = ${?AWS_KEYSPACES_LOCAL_DATACENTER}
    }
  }

  advanced {
    reconnect-on-init = true

    auth-provider {
      class = software.aws.mcs.auth.SigV4AuthProvider
      aws-region = ${?AWS_REGION}
    }

    ssl-engine-factory {
      class = DefaultSslEngineFactory
      truststore-path = ${?AWS_KEYSPACES_TRUSTSTORE_PATH}
      truststore-password = ${?AWS_KEYSPACES_TRUSTSTORE_PASSWORD}
    }
  }
}
